## What's new today?
* Let's learn about one of the most important concepts of joining datasets
  * Concatenation
  * Append
  * Merge
  * The above functions being done along different axes
  
![vert_join](img/merging_concat_keys.png)

![hor_join](img/merging_concat_axis1.png)

In [2]:
import pandas as pd
import numpy as np

In [3]:
# let's create 2 separate datasets grouped on match_location
df = pd.read_csv('data/iplfinal.csv',sep='|')
df.head()

,match_description,match_date,match_venue,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,balls,fours,sixes
0,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Rohit Sharma (c),c Rayudu b Watson,15,18,1,1
1,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Evin Lewis,lbw b D Chahar,0,2,0,0
2,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Ishan Kishan (wk),c Mark Wood b Tahir,40,29,4,1
3,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Suryakumar Yadav,c Harbhajan b Watson,43,29,6,1
4,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Hardik Pandya,not out,22,20,2,0

In [11]:
a = df.loc[:10]
b = df.loc[11:20]
c = df.loc[21:50]
d = [a,b,c]
d
e = pd.concat(d,keys=['a','b','c'],axis=0)

[                                    match_description  match_date  \
 0   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 1   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 2   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 3   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 4   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 5   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 6   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 7   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 8   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 9   Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 10  Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07

           match_venue match_location                      match_result  \
 0   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 1   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 2   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 3   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 4   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 5   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 6   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 7   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 8   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 9   Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt
 10  Wankhede Stadium,         Mumbai  Chennai Super Kings won by 1 wkt

                       team_name innings_order       batsman_name  \
 0        Mumbai Indians Innings     innings_1   Rohit Sharma (c)
 1        Mumbai Indians Innings     innings_1         Evin Lewis
 2        Mumbai Indians Innings     innings_1  Ishan Kishan (wk)
 3        Mumbai Indians Innings     innings_1   Suryakumar Yadav
 4        Mumbai Indians Innings     innings_1      Hardik Pandya
 5        Mumbai Indians Innings     innings_1      Krunal Pandya
 6   Chennai Super Kings Innings     innings_2       Shane Watson
 7   Chennai Super Kings Innings     innings_2      Ambati Rayudu
 8   Chennai Super Kings Innings     innings_2       Suresh Raina
 9   Chennai Super Kings Innings     innings_2       Kedar Jadhav
 10  Chennai Super Kings Innings     innings_2  MS Dhoni (c & wk)

                      dismissal_mode  runs  balls  fours  sixes
 0                 c Rayudu b Watson    15     18      1      1
 1                    lbw b D Chahar     0      2      0      0
 2               c Mark Wood b Tahir    40     29      4      1
 3              c Harbhajan b Watson    43     29      6      1
 4                           not out    22     20      2      0
 5                           not out    41     22      5      2
 6           c Lewis b Hardik Pandya    16     14      1      1
 7                    lbw b Markande    22     19      4      0
 8   c Krunal Pandya b Hardik Pandya     4      6      0      0
 9                           not out    24     22      1      2
 10                   lbw b Markande     5      5      0      0  ,
                                     match_description  match_date  \
 11  Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 12  Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 13  Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 14  Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 15  Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 16  Mumbai Indians vs Chennai Super Kings, 1st Mat...  2018-04-07
 17  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 18  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 19  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 20  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08

                                       match_venue match_location  \
 11                              Wankhede Stadium,         Mumbai
 12                              Wankhede Stadium,         Mumbai
 13                              Wankhede Stadium,         Mumbai
 14                              Wankhede Stadium,         Mumbai
 15                              Wankhede Stadium,         Mumbai
 16                              Wankhede Stadium,         Mumbai
 17  Punjab Cricket Association IS Bindra Stadium,         Mohali
 18  Punjab Cricket Association IS Bindra Stadium,         Mohali
 19  Punjab Cricket Association IS Bindra Stadium,         Mohali
 20  Punjab Cricket Association IS Bindra Stadium,         Mohali

                         match_result                    team_name  \
 11  Chennai Super Kings won by 1 wkt  Chennai Super Kings Innings
 12  Chennai Super Kings won by 1 wkt  Chennai Super Kings Innings
 13  Chennai Super Kings won by 1 wkt  Chennai Super Kings Innings
 14  Chennai Super Kings won by 1 wkt  Chennai Super Kings Innings
 15  Chennai Super Kings won by 1 wkt  Chennai Super Kings Innings
 16  Chennai Super Kings won by 1 wkt  Chennai Super Kings Innings
 17     Kings XI Punjab won by 6 wkts     Delhi Daredevils Innings
 18     Kings XI Punjab won by 6 wkts     Delhi Daredevils Innings
 19     Kings XI Punjab won by 6 wkts     Delhi Daredevils Innings
 20     Kings XI Punjab won by 6 wkts     Delhi Daredevils Innings

    innings_order        batsman_name                   dismissal_mode  runs  \
 11     innings_2     Ravindra Jadeja  c Suryakumar Yadav b Mustafizur    12
 12     innings_2        Dwayne Bravo                 c Rohit b Bumrah    68
 13     innings_2       Deepak Chahar       st Ishan Kishan b Markande     0
 14     innings_2     Harbhajan Singh           c Bumrah b McClenaghan     8
 15     innings_2           Mark Wood     c Mustafizur b Hardik Pandya     1
 16     innings_2         Imran Tahir                          not out     2
 17     innings_1         Colin Munro                     lbw b Mujeeb     4
 18     innings_1  Gautam Gambhir (c)                 run out (Mujeeb)    55
 19     innings_1        Shreyas Iyer                   c Rahul b Axar    11
 20     innings_1       Vijay Shankar            c Axar b Mohit Sharma    13

     balls  fours  sixes
 11     13      1      0
 12     30      3      7
 13      1      0      0
 14      5      1      0
 15      3      0      0
 16      2      0      0
 17      6      0      0
 18     42      5      1
 19     11      0      1
 20     13      0      0  ,
                                     match_description  match_date  \
 21  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 22  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 23  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 24  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 25  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 26  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 27  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 28  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 29  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 30  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 31  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 32  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 33  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 34  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 35  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 36  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 37  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 38  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 39  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 40  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 41  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 42  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 43  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 44  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 45  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 46  Kolkata Knight Riders vs Royal Challengers Ban...  2018-04-08
 47  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 48  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 49  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08
 50  Kings XI Punjab vs Delhi Daredevils, 2nd Match...  2018-04-08

                                       match_venue match_location  \
 21  Punjab Cricket Association IS Bindra Stadium,         Mohali
 22  Punjab Cricket Association IS Bindra Stadium,         Mohali
 23  Punjab Cricket Association IS Bindra Stadium,         Mohali
 24  Punjab Cricket Association IS Bindra Stadium,         Mohali
 25  Punjab Cricket Association IS Bindra Stadium,         Mohali
 26  Punjab Cricket Association IS Bindra Stadium,         Mohali
 27  Punjab Cricket Association IS Bindra Stadium,         Mohali
 28  Punjab Cricket Association IS Bindra Stadium,         Mohali
 29  Punjab Cricket Association IS Bindra Stadium,         Mohali
 30  Punjab Cricket Association IS Bindra Stadium,         Mohali
 31                                  Eden Gardens,        Kolkata
 32                                  Eden Gardens,        Kolkata
 33                                  Eden Gardens,        Kolkata
 34                                  Eden Gardens,        Kolkata
 35                                  Eden Gardens,        Kolkata
 36                                  Eden Gardens,        Kolkata
 37                                  Eden Gardens,        Kolkata
 38                                  Eden Gardens,        Kolkata
 39                                  Eden Gardens,        Kolkata
 40                                  Eden Gardens,        Kolkata
 41                                  Eden Gardens,        Kolkata
 42                                  Eden Gardens,        Kolkata
 43                                  Eden Gardens,        Kolkata
 44                                  Eden Gardens,        Kolkata
 45                                  Eden Gardens,        Kolkata
 46                                  Eden Gardens,        Kolkata
 47  Punjab Cricket Association IS Bindra Stadium,         Mohali
 48  Punjab Cricket Association IS Bindra Stadium,         Mohali
 49  Punjab Cricket Association IS Bindra Stadium,         Mohali
 50  Punjab Cricket Association IS Bindra Stadium,         Mohali

                            match_result                            team_name  \
 21        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings
 22        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings
 23        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings
 24        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings
 25        Kings XI Punjab won by 6 wkts              Kings XI Punjab Innings
 26        Kings XI Punjab won by 6 wkts              Kings XI Punjab Innings
 27        Kings XI Punjab won by 6 wkts              Kings XI Punjab Innings
 28        Kings XI Punjab won by 6 wkts              Kings XI Punjab Innings
 29        Kings XI Punjab won by 6 wkts              Kings XI Punjab Innings
 30        Kings XI Punjab won by 6 wkts              Kings XI Punjab Innings
 31  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 32  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 33  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 34  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 35  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 36  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 37  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 38  Kolkata Knight Riders won by 4 wkts  Royal Challengers Bangalore Innings
 39  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 40  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 41  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 42  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 43  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 44  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 45  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 46  Kolkata Knight Riders won by 4 wkts        Kolkata Knight Riders Innings
 47        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings
 48        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings
 49        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings
 50        Kings XI Punjab won by 6 wkts             Delhi Daredevils Innings

    innings_order             batsman_name                   dismissal_mode  \
 21     innings_1        Rishabh Pant (wk)            c Andrew Tye b Mujeeb
 22     innings_1            Rahul Tewatia                     lbw b Ashwin
 23     innings_1             Chris Morris                          not out
 24     innings_1         Daniel Christian                   b Mohit Sharma
 25     innings_2        Lokesh Rahul (wk)                  c Shami b Boult
 26     innings_2           Mayank Agarwal           c Shami b Chris Morris
 27     innings_2             Yuvraj Singh  c Vijay Shankar b Rahul Tewatia
 28     innings_2               Karun Nair              c Boult b Christian
 29     innings_2             David Miller                          not out
 30     innings_2           Marcus Stoinis                          not out
 31     innings_1         Brendon McCullum                         b Narine
 32     innings_1     Quinton de Kock (wk)           c Vinay Kumar b Chawla
 33     innings_1          Virat Kohli (c)                    b Nitish Rana
 34     innings_1           AB de Villiers          c Johnson b Nitish Rana
 35     innings_1            Sarfaraz Khan          c Rinku Singh b Johnson
 36     innings_1            Mandeep Singh    c Kuldeep Yadav b Vinay Kumar
 37     innings_1             Chris Woakes        c A Russell b Vinay Kumar
 38     innings_1        Washington Sundar                          not out
 39     innings_2             Sunil Narine                          b Umesh
 40     innings_2               Chris Lynn     c de Villiers b Chris Woakes
 41     innings_2            Robin Uthappa       c Brendon McCullum b Umesh
 42     innings_2              Nitish Rana          lbw b Washington Sundar
 43     innings_2  Dinesh Karthik (c & wk)                          not out
 44     innings_2              Rinku Singh         c de Kock b Chris Woakes
 45     innings_2            Andre Russell     c de Villiers b Chris Woakes
 46     innings_2              Vinay Kumar                          not out
 47     innings_1              Colin Munro                     lbw b Mujeeb
 48     innings_1       Gautam Gambhir (c)                 run out (Mujeeb)
 49     innings_1             Shreyas Iyer                   c Rahul b Axar
 50     innings_1            Vijay Shankar            c Axar b Mohit Sharma

     runs  balls  fours  sixes
 21    28     13      4      1
 22     9      7      1      0
 23    27     16      1      1
 24    13     13      0      1
 25    51     16      6      4
 26     7      5      0      1
 27    12     22      2      0
 28    50     33      5      2
 29    24     23      1      0
 30    22     15      2      0
 31    43     27      6      2
 32     4      4      1      0
 33    31     33      1      1
 34    44     23      1      5
 35     6     10      0      0
 36    37     18      4      2
 37     5      5      1      0
 38     0      0      0      0
 39    50     19      4      5
 40     5      8      1      0
 41    13     12      0      1
 42    34     25      2      2
 43    35     29      4      0
 44     6      6      1      0
 45    15     11      2      1
 46     6      3      1      0
 47     4      6      0      0
 48    55     42      5      1
 49    11     11      0      1
 50    13     13      0      0  ]

In [16]:
pd.concat([a,b],axis=1)

,match_description,match_date,match_venue,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,...,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,balls,fours,sixes
0,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Rohit Sharma (c),c Rayudu b Watson,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Evin Lewis,lbw b D Chahar,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Ishan Kishan (wk),c Mark Wood b Tahir,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Suryakumar Yadav,c Harbhajan b Watson,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Hardik Pandya,not out,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Krunal Pandya,not out,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Shane Watson,c Lewis b Hardik Pandya,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Ambati Rayudu,lbw b Markande,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Suresh Raina,c Krunal Pandya b Hardik Pandya,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Kedar Jadhav,not out,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,MS Dhoni (c & wk),lbw b Markande,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Ravindra Jadeja,c Suryakumar Yadav b Mustafizur,12.0,13.0,1.0,0.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Dwayne Bravo,c Rohit b Bumrah,68.0,30.0,3.0,7.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Deepak Chahar,st Ishan Kishan b Markande,0.0,1.0,0.0,0.0
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Harbhajan Singh,c Bumrah b McClenaghan,8.0,5.0,1.0,0.0
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Mark Wood,c Mustafizur b Hardik Pandya,1.0,3.0,0.0,0.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Imran Tahir,not out,2.0,2.0,0.0,0.0
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Colin Munro,lbw b Mujeeb,4.0,6.0,0.0,0.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Gautam Gambhir (c),run out (Mujeeb),55.0,42.0,5.0,1.0
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Shreyas Iyer,c Rahul b Axar,11.0,11.0,0.0,1.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Vijay Shankar,c Axar b Mohit Sharma,13.0,13.0,0.0,0.0

In [17]:
a.append(b)
a.append([b,c])

,match_description,match_date,match_venue,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,balls,fours,sixes
0,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Rohit Sharma (c),c Rayudu b Watson,15,18,1,1
1,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Evin Lewis,lbw b D Chahar,0,2,0,0
2,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Ishan Kishan (wk),c Mark Wood b Tahir,40,29,4,1
3,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Suryakumar Yadav,c Harbhajan b Watson,43,29,6,1
4,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Hardik Pandya,not out,22,20,2,0
5,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Krunal Pandya,not out,41,22,5,2
6,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Shane Watson,c Lewis b Hardik Pandya,16,14,1,1
7,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Ambati Rayudu,lbw b Markande,22,19,4,0
8,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Suresh Raina,c Krunal Pandya b Hardik Pandya,4,6,0,0
9,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Kedar Jadhav,not out,24,22,1,2
10,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,MS Dhoni (c & wk),lbw b Markande,5,5,0,0
11,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Ravindra Jadeja,c Suryakumar Yadav b Mustafizur,12,13,1,0
12,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Dwayne Bravo,c Rohit b Bumrah,68,30,3,7
13,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Deepak Chahar,st Ishan Kishan b Markande,0,1,0,0
14,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Harbhajan Singh,c Bumrah b McClenaghan,8,5,1,0
15,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Mark Wood,c Mustafizur b Hardik Pandya,1,3,0,0
16,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Chennai Super Kings Innings,innings_2,Imran Tahir,not out,2,2,0,0
17,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Colin Munro,lbw b Mujeeb,4,6,0,0
18,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Gautam Gambhir (c),run out (Mujeeb),55,42,5,1
19,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Shreyas Iyer,c Rahul b Axar,11,11,0,1
20,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Vijay Shankar,c Axar b Mohit Sharma,13,13,0,0
21,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Rishabh Pant (wk),c Andrew Tye b Mujeeb,28,13,4,1
22,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Rahul Tewatia,lbw b Ashwin,9,7,1,0
23,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Chris Morris,not out,27,16,1,1
24,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Daniel Christian,b Mohit Sharma,13,13,0,1
25,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Kings XI Punjab Innings,innings_2,Lokesh Rahul (wk),c Shami b Boult,51,16,6,4
26,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Kings XI Punjab Innings,innings_2,Mayank Agarwal,c Shami b Chris Morris,7,5,0,1
27,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Kings XI Punjab Innings,innings_2,Yuvraj Singh,c Vijay Shankar b Rahul Tewatia,12,22,2,0
28,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Kings XI Punjab Innings,innings_2,Karun Nair,c Boult b Christian,50,33,5,2
29,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Kings XI Punjab Innings,innings_2,David Miller,not out,24,23,1,0
30,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Kings XI Punjab Innings,innings_2,Marcus Stoinis,not out,22,15,2,0
31,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Brendon McCullum,b Narine,43,27,6,2
32,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Quinton de Kock (wk),c Vinay Kumar b Chawla,4,4,1,0
33,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Virat Kohli (c),b Nitish Rana,31,33,1,1
34,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,AB de Villiers,c Johnson b Nitish Rana,44,23,1,5
35,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Sarfaraz Khan,c Rinku Singh b Johnson,6,10,0,0
36,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Mandeep Singh,c Kuldeep Yadav b Vinay Kumar,37,18,4,2
37,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Chris Woakes,c A Russell b Vinay Kumar,5,5,1,0
38,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Washington Sundar,not out,0,0,0,0
39,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Sunil Narine,b Umesh,50,19,4,5
40,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Chris Lynn,c de Villiers b Chris Woakes,5,8,1,0
41,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Robin Uthappa,c Brendon McCullum b Umesh,13,12,0,1
42,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Nitish Rana,lbw b Washington Sundar,34,25,2,2
43,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Dinesh Karthik (c & wk),not out,35,29,4,0
44,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Rinku Singh,c de Kock b Chris Woakes,6,6,1,0
45,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Andre Russell,c de Villiers b Chris Woakes,15,11,2,1
46,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Kolkata Knight Riders Innings,innings_2,Vinay Kumar,not out,6,3,1,0
47,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Colin Munro,lbw b Mujeeb,4,6,0,0
48,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Gautam Gambhir (c),run out (Mujeeb),55,42,5,1
49,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Shreyas Iyer,c Rahul b Axar,11,11,0,1
50,"Kings XI Punjab vs Delhi Daredevils, 2nd Match...",2018-04-08,"Punjab Cricket Association IS Bindra Stadium,",Mohali,Kings XI Punjab won by 6 wkts,Delhi Daredevils Innings,innings_1,Vijay Shankar,c Axar b Mohit Sharma,13,13,0,0

In [18]:
df1 = pd.DataFrame({'a':[1,2,3,4],
                    'b':[5,6,7,8],
                    'c':[9,10,11,12]})
#df2 = pd.DataFrame({'a':[5,6,1,1],
#                    'b':[5,7,2,0],
#                    'c':[9,4,2,7]})
#df3 = pd.concat([df1,df2],keys=['first','second'])
df1
#df3.loc['second']
#repeating the keys. how?

   a  b   c
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [20]:
sr1 = pd.Series([20,21,22,23])
sr1

0    20
1    21
2    22
3    23
dtype: int64

In [22]:
df2 = pd.concat([df1,sr1],axis=1)
df2

   a  b   c   0
0  1  5   9  20
1  2  6  10  21
2  3  7  11  22
3  4  8  12  23

In [23]:
sr2 = pd.Series([41,42,43,44],name='d')
df2 = pd.concat([df1,sr2],axis=1)
df2

   a  b   c   d
0  1  5   9  41
1  2  6  10  42
2  3  7  11  43
3  4  8  12  44

In [21]:
df4 = pd.DataFrame({'a':[5,6,4],'b':[4,1,9]},index=[2,3,5])
df4

   a  b
2  5  4
3  6  1
5  4  9

In [22]:
#pd.concat([df1,df4])
pd.concat([df1,df4],axis=1)
#pd.concat([df1,df4],ignore_index=True)

     a    b     c    a    b
0  1.0  5.0   9.0  NaN  NaN
1  2.0  6.0  10.0  NaN  NaN
2  3.0  7.0  11.0  5.0  4.0
3  4.0  8.0  12.0  6.0  1.0
5  NaN  NaN   NaN  4.0  9.0

In [23]:
df6 = pd.concat([df1,df4],axis=1,join='inner')
df6

   a  b   c  a  b
2  3  7  11  5  4
3  4  8  12  6  1

In [66]:
pd.merge(df1,df4,how='inner',left_index=True,right_index=True)

   a  b   c  d  e
2  3  7  11  5  4
3  4  8  12  6  1

In [67]:
pd.merge(df1,df4,how='left',left_index=True,right_index=True)

   a  b   c    d    e
0  1  5   9  NaN  NaN
1  2  6  10  NaN  NaN
2  3  7  11  5.0  4.0
3  4  8  12  6.0  1.0

In [68]:
pd.merge(df1,df4,how='right',left_index=True,right_index=True)

     a    b     c  d  e
2  3.0  7.0  11.0  5  4
3  4.0  8.0  12.0  6  1
5  NaN  NaN   NaN  4  9

In [69]:
pd.merge(df4,df1,how='outer',left_index=True,right_index=True)

     d    e    a    b     c
0  NaN  NaN  1.0  5.0   9.0
1  NaN  NaN  2.0  6.0  10.0
2  5.0  4.0  3.0  7.0  11.0
3  6.0  1.0  4.0  8.0  12.0
5  4.0  9.0  NaN  NaN   NaN

## Another method of joining 
* Joining on keys

In [70]:
df1.join(df4)

   a  b   c    d    e
0  1  5   9  NaN  NaN
1  2  6  10  NaN  NaN
2  3  7  11  5.0  4.0
3  4  8  12  6.0  1.0

In [71]:
df1.join(df4,how='inner')

   a  b   c  d  e
2  3  7  11  5  4
3  4  8  12  6  1

In [72]:
df1.join(df4,how='right')

     a    b     c  d  e
2  3.0  7.0  11.0  5  4
3  4.0  8.0  12.0  6  1
5  NaN  NaN   NaN  4  9

In [73]:
df1.join(df4,how='outer')

     a    b     c    d    e
0  1.0  5.0   9.0  NaN  NaN
1  2.0  6.0  10.0  NaN  NaN
2  3.0  7.0  11.0  5.0  4.0
3  4.0  8.0  12.0  6.0  1.0
5  NaN  NaN   NaN  4.0  9.0